version: '3.8'

services:
  quiz_ai_app-db:
    image: postgres:15.3
    container_name: quiz_ai_app-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quiz_ai_app_db  
    volumes:
      - ./postgres:/var/lib/postgresql/data