services:
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: quiz-ai-sql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=contraseniaSegura123!
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data: